# FROM golang:1.22-alpine as builder
# RUN mkdir /app
# COPY . /app
#
# WORKDIR /app
# RUN CGO_ENABLED=0 go build -o listenerApp .
# RUN chmod +x /app/listenerApp

FROM alpine:latest
RUN mkdir /app
COPY listenerApp /app
CMD ["/app/listenerApp"]


